// <auto-generated />
namespace SmartDevices.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddTypetoSmartDevices : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTypetoSmartDevices));
        
        string IMigrationMetadata.Id
        {
            get { return "201808092133306_Add Type to Smart Devices"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
